algoritmo "semnome"
var
 D: inteiro
inicio
escreval ("--------------------------")
escreval ("    CRIANÇA ESPERANÇA")
escreval ("--------------------------")
escreval ("muito obrigado por ajudar ")
escreval (" [1] para doar R$10 ")
escreval (" [2] para doar R$25 ")
escreval (" [3] para doar R$50 ")
escreval (" [4] para doar outros valores ")
escreval (" [5] para cancelar ")
leia (D)
escolha (D)
caso 1

caso 2




fimescolha
fimalgoritmo